### ISSUE TITLE
Unable to register card

### ISSUE THREAD

**Issue by Joohelmer** [lancygoyal/mangopay-client-react#1]
Hi, 

I have found a bug. I'm not able to register card.
The reponse is : {"timestamp":"2020-04-13T14:02:10.887+0000","status":415,"error":"Unsupported Media Type","message":"Content type 'application/json' not supported","path":"/getToken"}

So to resolve the problem, see below : 
![Capture d’écran 2020-04-13 à 16 11 20](https://user-images.githubusercontent.com/6428710/79127170-b1896680-7da1-11ea-9e32-2c34dbb0c38b.png)

**Comment by lancygoyal** [comment]
Hi Jon, If you raise PR for the same that will be helpful. Thanks
